### ISSUE TITLE
Keeping the app.js file size small

### ISSUE THREAD

**Issue by jekibus** [brtheo/ServerWebComponent-htmx-lit-bun-elysia#1]
Thank you, this repo is very helpful.
Ask: When I create or update component content, public/app.js content will add or update too. If we have many component, a large file will be created, what should we do to keep the js file size small?

**Comment by brtheo** [comment]
Hello @jekibus, what can be done here would be to do code splitting with dynamic imports for example. I'm not sure but it should be configurable within Bun's builder macro

**Comment by jekibus** [comment]
Thank @brtheo I will try to read that
